## Exercice 1 - Analyse de notes d’étudiants

In [1]:
import numpy as np

np.random.seed(455) # fixer la seed
notes = np.random.randint(0,20, size=(84, 8))

print('Informations générales')
print(f'shape: {notes.shape}')
print(f'dtype: {notes.dtype}')

notes = notes.astype(np.int8)
print(f'\ntype après modification: {notes.dtype}')

print("nombres d'étudiants: " + str(notes.shape[0]))
print("nombres de matières: " + str(notes.shape[1]))


print('\nTableau de notes\n')
print(notes)

Informations générales
shape: (84, 8)
dtype: int32

type après modification: int8
nombres d'étudiants: 84
nombres de matières: 8

Tableau de notes

[[16  5  8  0 11 14 12  6]
 [11 13  1 19 18  9 16 17]
 [ 4  2  0  3 11  5  5  2]
 [ 8  9  7  1  5 14  3  9]
 [ 2  6 18  4 15  2  3 18]
 [ 6  4  0  5 10  1 11 14]
 [14 18  8  6  4 15 11  6]
 [ 5 19 10 14 11 18  9  9]
 [13 17  5 17 17  4  3 17]
 [10  2  7  2 12  8 19 15]
 [19 11  3  9 17 13 18 14]
 [ 0 10 16 12 19  0 14  5]
 [17  1  6 15  0 18 10  1]
 [10 18  9  7  6 10  1  8]
 [ 5 16  4 18  9  4 19  7]
 [ 2 19  7  5  3 13  6  6]
 [ 7 17  1 19  5 18  4 14]
 [ 6 14  7  6  8  2  1  0]
 [ 6  1 14 15  9  0  9 12]
 [14  4  5  0 10  3  2  4]
 [16 12 17 19 14  8  7  6]
 [ 6 11 11  0 18 16 10  5]
 [11  5 17 16  9 16 18 10]
 [18 17 11  8  8 12 11 16]
 [13 10  9  1  2  0 12  1]
 [ 3 13  0 17  9 11 16 17]
 [18 14 14  5  2  8 17 15]
 [ 5  3 19 18  2 16  3 11]
 [ 0  3 14 12 13 15 15  8]
 [15 19  3 17 18 17 14 18]
 [15 11  1  6 19 10  1 11]
 [15 19 11 17 1

#### Partie 2 — Statistiques

In [2]:
#Calculer :
    #moyenne globale
    #moyenne par étudiant
    #moyenne par matière
    #note maximale par matière
    #note minimale pour la 5ème matière

mean_all = notes.mean()
print("moyenne globale:", str(mean_all))

student_mean = notes.mean(axis=1)
print('\nmoyenne par étudiant: {}'.format(student_mean))

mat_mean = notes.mean(axis=0)
print('\nmoyenne par matière: {}'.format(mat_mean))

max_note_per_mat = notes.max(axis=0, keepdims=True)
print(f'\nnote maximale par matière: \n{max_note_per_mat}')

min_mat_5 = notes[4].min()
print('\nnote minimale pour la 5ème matière:', str(min_mat_5))

moyenne globale: 9.989583333333334

moyenne par étudiant: [ 9.    13.     4.     7.     8.5    6.375 10.25  11.875 11.625  9.375
 13.     9.5    8.5    8.625 10.25   7.625 10.625  5.5    8.25   5.25
 12.375  9.625 12.75  12.625  6.    10.75  11.625  9.625 10.    15.125
  9.25  12.125 11.25   9.375 10.375  9.125 14.5   12.125 10.5    9.5
  9.125 11.25   9.125  8.5   12.    10.     8.625 10.875 11.    13.
  9.25  13.25   9.     4.375 12.25   6.375  7.75   8.125  7.875  8.25
  9.875 13.5   11.75  10.     6.375 11.875 11.625 10.25   8.75  12.75
 13.625 10.25   9.625 11.875  7.375  7.375  8.875 10.625 14.    15.
  8.5   10.375  8.5    9.625]

moyenne par matière: [10.39285714 10.26190476 10.07142857  9.58333333  9.91666667 10.21428571
  9.20238095 10.27380952]

note maximale par matière: 
[[19 19 19 19 19 19 19 19]]

note minimale pour la 5ème matière: 2


#### Partie 3 — Filtrage avec masques

In [3]:
"""Créer :
- un masque des notes > 10
- un masque des étudiants admis (moyenne >= 10)"""


mask_great_10 = notes>10
notes_sup_10 = notes[mask_great_10]

mask_admis = notes.mean(axis=1) >= 10
print(mask_admis)
nb_admis = notes[mask_admis].shape[0]
print("On a donc : {} admis".format(nb_admis))

[False  True False False False False  True  True  True False  True False
 False False  True False  True False False False  True False  True  True
 False  True  True False  True  True False  True  True False  True False
  True  True  True False False  True False False  True  True False  True
  True  True False  True False False  True False False False False False
 False  True  True  True False  True  True  True False  True  True  True
 False  True False False False  True  True  True False  True False False]
On a donc : 42 admis


#### Partie 4 — Bonus NumPy réel

In [4]:
#Ajouter un bonus de : +2 points à toutes les notes avec broadcasting

notes = notes + 2
notes = np.where(notes > 20, 20, notes)
print(notes)

[[18  7 10  2 13 16 14  8]
 [13 15  3 20 20 11 18 19]
 [ 6  4  2  5 13  7  7  4]
 [10 11  9  3  7 16  5 11]
 [ 4  8 20  6 17  4  5 20]
 [ 8  6  2  7 12  3 13 16]
 [16 20 10  8  6 17 13  8]
 [ 7 20 12 16 13 20 11 11]
 [15 19  7 19 19  6  5 19]
 [12  4  9  4 14 10 20 17]
 [20 13  5 11 19 15 20 16]
 [ 2 12 18 14 20  2 16  7]
 [19  3  8 17  2 20 12  3]
 [12 20 11  9  8 12  3 10]
 [ 7 18  6 20 11  6 20  9]
 [ 4 20  9  7  5 15  8  8]
 [ 9 19  3 20  7 20  6 16]
 [ 8 16  9  8 10  4  3  2]
 [ 8  3 16 17 11  2 11 14]
 [16  6  7  2 12  5  4  6]
 [18 14 19 20 16 10  9  8]
 [ 8 13 13  2 20 18 12  7]
 [13  7 19 18 11 18 20 12]
 [20 19 13 10 10 14 13 18]
 [15 12 11  3  4  2 14  3]
 [ 5 15  2 19 11 13 18 19]
 [20 16 16  7  4 10 19 17]
 [ 7  5 20 20  4 18  5 13]
 [ 2  5 16 14 15 17 17 10]
 [17 20  5 19 20 19 16 20]
 [17 13  3  8 20 12  3 13]
 [17 20 13 19 18 12  4  9]
 [ 6 14 16 20 19  8  5 18]
 [20 11 17  3  4  6  9 20]
 [13  3 20 15 12 15  6 15]
 [16  4 12  4 13 11 10 19]
 [19 17 15 17 13 20 15 15]
 